### ISSUE TITLE
[question] 공동 작성이 Clone 으로 하면 되는건가요?

### ISSUE THREAD

**Issue by namseokyoo** [namseokyoo/bookshelf#1]
@hyunsung-kim 튜터님! 저희 공동 작성으로 해보려고 Clone 누르고 링크 공유했는데
@kijaewon 여기에 fork된걸로만 나오는데 이게 공동 작업이 맞는건가 싶네요~!

**Comment by hyunsung-kim** [comment]
남석님 코드 베이스(codebase)에서 재원님이 clone해 가셨다면 공동 소스를 사용한 것입니다. 
근데 fork 해 가시면 각자 코드 베이스 사용하는 겁니다. 

정리: @namseokyoo  Github에서 @kijaewon 님이 clone해서 작업하고 업로드하면 됩니다.

**Comment by kijaewon** [comment]
@hyunsung-kim  제가 업로드하려면 write access가 필요하다고 나오는데 어떻게 해야하나요???

**Comment by namseokyoo** [comment]
@kijaewon 재원님 검색해보니 Collabolator 등록해야한다해서, 일단 등록해봤는데 다시 한번 시도 부탁드려요~

**Comment by hyunsung-kim** [comment]
확인해 볼게요

**Comment by kijaewon** [comment]
collaborator 되니깐 잘 올라갑니다!!!
