### ISSUE TITLE
[request] 랜딩 페이지(최초 사용자가 진입하는 화면)를 디자인하고 필요한 기능을 구현해 주세요.

### ISSUE THREAD

**Issue by hyunsung-kim** [namseokyoo/bookshelf#2]
너무 쉽게 하셔서 다음 과제를 드려야 할거 같네요.

1. README.md 파일에 작성한 기능 중에 랜딩 페이지 작업을 시작해 주세요.
2. 각자가 맡은 기능을 구현해서 올려주세요.

다음 시간에 각자 브랜치로 작업하시는 방법을 알려드릴게요.

@namseokyoo @kijaewon 축하드립니다. :tada:

**Comment by namseokyoo** [comment]
@hyunsung-kim 감사합니다!! 👏 랜딩페이지 시작해보겠습니다~
 
@kijaewon 재원님 랜딩페이지는 발표자료에 만들어주신거 바탕으로 제가 구성해보겠습니다. 확인해주신 API 사용하는 부분 연결하면 될꺼 같아요!
