### ISSUE TITLE
[Request]Pull request conflict

### ISSUE THREAD

**Issue by kijaewon** [namseokyoo/bookshelf#23]
conflict  발생해서 해결하는데로 쳐봤는데.. master에 이상하게 올라간거같아요...
@hyunsung-kim 
@namseokyoo

**Comment by kijaewon** [comment]
master에 app.py랑 review.html이 다른내용으로 두번들어가있네요..

**Comment by hyunsung-kim** [comment]
해결 되었나요?

**Comment by kijaewon** [comment]
넵!!
