### ISSUE TITLE
[TASK] branch 만들어서 올려봤습니다.

### ISSUE THREAD

**Issue by kijaewon** [namseokyoo/bookshelf#6]
파이썬에서 API정보 처리하고 dotenv까지 활용한 파일이랑 랜딩페이지 선택옵션으로 바꾼거 브랜치 따로 만들어서 올려두었습니다. 혹시 남석님도 보실수 있는건지 확인해주세요.

**Comment by namseokyoo** [comment]
branch 구분해서 보이네요~!

**Comment by namseokyoo** [comment]
튜터님께 Branch  하신거 Master에 pull request 하는거 배워서 진행했습니다!

**Comment by kijaewon** [comment]
확인했습니다!
